// a432.vortex.addresses.ts — every address on the full vortex past the orbit, loadable by name
// GENERATED by scripts/a432-orbit-fill.mjs from the shortest existing member; do not edit by hand.
//
// The orbit's own addresses live in a432.orbit.ts. These are the ones the
// doubling map does not reach: the axis, and the return to the seed.

/** The full-vortex addresses beyond the orbit, shortest first. */
export const VORTEX_ADDRESSES = [
  '1.2.4.8.7.5.3',
  '1.2.4.8.7.5.3.6',
  '1.2.4.8.7.5.3.6.9',
  '1.2.4.8.7.5.3.6.9.1',
] as const

export type VortexAddress = typeof VORTEX_ADDRESSES[number]

/** Address to module, with literal paths so a static reader can follow them. */
export const VORTEX_HANDLES: Record<string, () => Promise<unknown>> = {
  '1.2.4.8.7.5.3': () => import('./a432.1.2.4.8.7.5.3.ts'),
  '1.2.4.8.7.5.3.6': () => import('./a432.1.2.4.8.7.5.3.6.ts'),
  '1.2.4.8.7.5.3.6.9': () => import('./a432.1.2.4.8.7.5.3.6.9.ts'),
  '1.2.4.8.7.5.3.6.9.1': () => import('./a432.1.2.4.8.7.5.3.6.9.1.ts'),
}

/** Load an address and return the sequence it holds. */
export async function loadVortexAddress(address: string): Promise<readonly number[]> {
  const handle = VORTEX_HANDLES[address]
  if (handle === undefined) throw new Error(`a432.vortex: no handle at address ${address}`)
  const mod = await handle() as { getVortexSequence?: () => readonly number[] }
  const seq = mod.getVortexSequence?.()
  if (seq === undefined) throw new Error(`a432.vortex: the module at ${address} holds no sequence`)
  return seq
}
