// a432.orbit.ts — every address on the doubling orbit, loadable by name
// GENERATED by scripts/a432-orbit-fill.mjs from the shortest existing member; do not edit by hand.
//
// The orbit modules all export the same names, so they cannot be re-exported
// from a432.index.ts. They are reached by ADDRESS instead: this is the map from
// an address to the module that holds it, with literal paths so a static reader
// can follow them.

/** Every address on the orbit, shortest first. */
export const ORBIT_ADDRESSES = [
  '1',
  '1.2',
  '1.2.4',
  '1.2.4.8',
  '1.2.4.8.7',
  '1.2.4.8.7.5',
] as const

export type OrbitAddress = typeof ORBIT_ADDRESSES[number]

/** Load the module at an address. The name is the handle; this unpacks it. */
export const ORBIT_HANDLES: Record<string, () => Promise<unknown>> = {
  '1': () => import('./a432.1.ts'),
  '1.2': () => import('./a432.1.2.ts'),
  '1.2.4': () => import('./a432.1.2.4.ts'),
  '1.2.4.8': () => import('./a432.1.2.4.8.ts'),
  '1.2.4.8.7': () => import('./a432.1.2.4.8.7.ts'),
  '1.2.4.8.7.5': () => import('./a432.1.2.4.8.7.5.ts'),
}

/**
 * Load an address and return the sequence it holds. A handle carries its load
 * implicitly, so this is the whole of what "reading" one means.
 */
export async function loadOrbitAddress(address: string): Promise<readonly number[]> {
  const handle = ORBIT_HANDLES[address]
  if (handle === undefined) throw new Error(`a432.orbit: no handle at address ${address}`)
  const mod = await handle() as { getOpenDoublingSequence?: () => number[] }
  const seq = mod.getOpenDoublingSequence?.()
  if (seq === undefined) throw new Error(`a432.orbit: the module at ${address} holds no sequence`)
  return seq
}
