// a432.1.2.4.8.7.5.3.6.9.1.ts — Full Vortex Address Module
// GENERATED by scripts/a432-orbit-fill.mjs from the shortest existing member; do not edit by hand.
//
// This module holds the first 10 digits of the full vortex sequence
// 1-2-4-8-7-5-3-6-9: the doubling orbit 1-2-4-8-7-5 followed by the axis, and then the return to the seed.
//
// DOUBLING ALONE DOES NOT PRODUCE THIS TAIL, which is why this family has its
// own module rather than reusing the open-doubling one. From 1 the doubling map
// closes on the six-cycle and returns to 1 — the seventh digit is 1, not 3 — so
// iterating it never reaches the axis.
//
// BUT THE TAIL IS DERIVED, NOT MERELY DECLARED, and an earlier version of this
// comment said otherwise. The axis is the REFLECTION of the orbit through the
// void: throughVoid is 1<->9, 2<->8, 3<->7, 4<->6 with 5 fixed, and
//
//     throughVoid(orbit[4]) = throughVoid(7) = 3
//     throughVoid(orbit[2]) = throughVoid(4) = 6
//     throughVoid(orbit[0]) = throughVoid(1) = 9
//
// so 3-6-9 is exactly the reflection of every second orbit element, read
// backwards. Every digit carries its reflection; the axis is where the orbit's
// reflections land. The suite asserts that relation against the kernel's own
// arrays rather than leaving it as prose here.
//
// The sequence is read from VORTEX_SEQUENCE because that constant states the
// concatenation once, not because there is no rule behind it.
//
// The tail past the orbit here is 3-6-9-1.

import { VORTEX_SEQUENCE } from '../../../../../../../../../../../kernel/index.ts'

/** The full vortex, closed back onto its seed. */
const CYCLE: readonly number[] = [...VORTEX_SEQUENCE, VORTEX_SEQUENCE[0]!]

/** The sequence this address holds. */
export function getVortexSequence(length = 10): readonly number[] {
  return CYCLE.slice(0, length)
}

/** The digit at a position, without materialising the prefix. */
export function getVortexNth(index = 0): number {
  const d = CYCLE[index]
  if (d === undefined) throw new Error(`a432.1.2.4.8.7.5.3.6.9.1: no digit at position ${index}`)
  return d
}

/** Where the orbit ends and the axis begins in this address. */
export const VORTEX_ORBIT_LENGTH = 6

export const a432VortexAddress = {
  address: '1.2.4.8.7.5.3.6.9.1',
  sequence: getVortexSequence,
  nth: getVortexNth,
  orbitLength: VORTEX_ORBIT_LENGTH,
  doc: `The first 10 digits of the full vortex 1-2-4-8-7-5-3-6-9: the doubling orbit, then the axis. Doubling alone does not reach the axis.`,
}
