# Jekyll configuration for ZeroPoint Node Documentation

title: ZeroPoint Node Documentation

# All documentation is now in src/0/
description: Complete documentation for the ZeroPoint Node consciousness system (harmonized in src/0/)
theme: jekyll-theme-cayman

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-redirect-from

# Relative links
relative_links:
  enabled: true

# Only src/0/ is the documentation root
collections:
  docs:
    output: true
    permalink: /src/0/:path/

# Defaults
defaults:
  - scope:
      path: "src/0/"
      type: "docs"
    values:
      layout: "default"

# Redirects
redirect_from:
  "/": "/src/0/"
