# ZeroPoint Node - Static Site Configuration
# Disable Jekyll processing to serve static files directly

# Disable Jekyll processing
plugins: []

# Serve static files from root
include: []

# Exclude unnecessary files
exclude:
  - node_modules
  - .git
  - .github
  - docs
  - src
  - tests
  - scripts
  - coverage
  - reports
  - data
  - analysis
  - deployment
  - learning-analytics
  - logs
  - .DS_Store
  - .eslintrc.js
  - .eslintrc.json
  - .eslintignore
  - .npmrc
  - jest.config.js
  - README.md
  - fix-typescript-errors.js

# Base URL configuration
baseurl: ""
url: ""

# Markdown processing
markdown: kramdown
highlighter: rouge

# No Jekyll processing
jekyll: false
