/**
 * What the Lean kernel says about each statement in LEAN_PROOFS.
 *
 * GENERATED by npm run lean:ledger from the .lean files. Do not edit: the
 * status of a theorem is a fact about a file, and a hand-kept copy of it is
 * exactly the drift lean:check exists to catch. Eight entries in a constant
 * named LEAN_PROOFS had proofs that are `sorry` in the file, and nothing
 * recorded it.
 *
 *   proven             the kernel accepted the file and the proof has no sorry
 *   sorry              the statement is written down and not proved
 *   unverifiable-here  the file imports a library this repository cannot build
 *   absent             no .lean file declares it
 */
export type LeanKernelStatus = 'proven' | 'sorry' | 'unverifiable-here' | 'rejected' | 'absent'

export const LEAN_STATUS: Readonly<Record<string, LeanKernelStatus>> = {
  "hadamard_squared": "unverifiable-here",
  "hadamard_unitary": "sorry",
  "pauliX_anticommute_pauliY": "unverifiable-here",
  "born_rule_sum": "unverifiable-here",
  "grover_amplification": "sorry",
  "grover_speedup": "sorry",
  "qft_unitary": "sorry",
  "phase_estimation_accuracy": "sorry",
  "repetition_detects_error": "sorry",
  "surface_code_threshold": "sorry",
  "tensor_preserves_norm": "sorry",
  "kyber_security": "unverifiable-here"
} as const

/**
 * Of the 12 theorems LEAN_PROOFS states in TypeScript, how many the kernel
 * has accepted. NOT the whole corpus: these twelve all live in files that import
 * Mathlib, so none of them is checkable here and the count is honestly zero.
 * A reader who takes this for the corpus concludes nothing is proved, which is
 * why the corpus totals are named separately below.
 */
export const LEAN_PROVEN_COUNT = 0
/** Of those same 12: written down and not proved. A sorry is not a proof. */
export const LEAN_SORRY_COUNT = 8

/** Every theorem in lean/, across all files. */
export const LEAN_CORPUS_THEOREM_COUNT = 79
/** Of those: accepted by the kernel, with axiom dependencies inside the allowed set. */
export const LEAN_CORPUS_PROVEN_COUNT = 55
