/**
 * What the Lean kernel says about each statement in LEAN_PROOFS.
 *
 * GENERATED by npm run lean:ledger from the .lean files. Do not edit: the
 * status of a theorem is a fact about a file, and a hand-kept copy of it is
 * exactly the drift lean:check exists to catch. Eight entries in a constant
 * named LEAN_PROOFS had proofs that are `sorry` in the file, and nothing
 * recorded it.
 *
 *   proven             the kernel accepted the file and the proof has no sorry
 *   sorry              the statement is written down and not proved
 *   unverifiable-here  the file imports a library this repository cannot build
 *   absent             no .lean file declares it
 */
export type LeanKernelStatus = 'proven' | 'sorry' | 'unverifiable-here' | 'rejected' | 'absent'

export const LEAN_STATUS: Readonly<Record<string, LeanKernelStatus>> = {
  "hadamard_squared": "unverifiable-here",
  "hadamard_unitary": "sorry",
  "pauliX_anticommute_pauliY": "unverifiable-here",
  "born_rule_sum": "unverifiable-here",
  "grover_amplification": "sorry",
  "grover_speedup": "sorry",
  "qft_unitary": "sorry",
  "phase_estimation_accuracy": "sorry",
  "repetition_detects_error": "sorry",
  "surface_code_threshold": "sorry",
  "tensor_preserves_norm": "sorry",
  "kyber_security": "unverifiable-here"
} as const

/** How many of the stated theorems the kernel has actually accepted. */
export const LEAN_PROVEN_COUNT = 0
/** Theorems written down and not proved. A sorry is not a proof. */
export const LEAN_SORRY_COUNT = 8
