/**
 * Configuration Constants for ZeroPoint Node
 *
 * Re-exports all configuration constants from the centralized SharedConstants.
 * This file maintains backward compatibility while ensuring all constants
 * are unified in the single source of truth.
 */

// Re-export all constants from SharedConstants
export {
  VORTEX_CONSTANTS,
  CONSCIOUSNESS_CONSTANTS,
  EMERGENCE_CONSTANTS,
  NETWORK_CONSTANTS,
  MATH_CONSTANTS,
  CONFIG_CONSTANTS,
  METAPHYSICAL_CONSTANTS,
  ConstantsUtils,
} from "../core/SharedConstants";

// Legacy exports for backward compatibility
export const GOLDEN_RATIO = VORTEX_CONSTANTS.GOLDEN_RATIO;
export const GOLDEN_CACHE_SIZE = CONFIG_CONSTANTS.GOLDEN_CACHE_SIZE;
export const GOLDEN_CACHE_TTL = CONFIG_CONSTANTS.GOLDEN_CACHE_TTL;
export const GOLDEN_CACHE_CLEANUP_INTERVAL = CONFIG_CONSTANTS.GOLDEN_CACHE_CLEANUP_INTERVAL;
export const RESONANCE_CACHE_SIZE = CONFIG_CONSTANTS.RESONANCE_CACHE_SIZE;
export const RESONANCE_CACHE_TTL = CONFIG_CONSTANTS.RESONANCE_CACHE_TTL;
export const HEALTH_CHECK_INTERVAL = CONFIG_CONSTANTS.HEALTH_CHECK_INTERVAL;
export const HEALTH_TIMEOUT = CONFIG_CONSTANTS.HEALTH_TIMEOUT;
export const HEALTH_ALERT_MEMORY = CONFIG_CONSTANTS.HEALTH_ALERT_MEMORY;
export const HEALTH_ALERT_CPU = CONFIG_CONSTANTS.HEALTH_ALERT_CPU;
export const HEALTH_ALERT_ERROR_RATE = CONFIG_CONSTANTS.HEALTH_ALERT_ERROR_RATE;
export const HEALTH_ALERT_RESPONSE_TIME = CONFIG_CONSTANTS.HEALTH_ALERT_RESPONSE_TIME;
export const DEFAULT_DEVICE_TYPE = CONFIG_CONSTANTS.DEFAULT_DEVICE_TYPE;
export const DEFAULT_NETWORK_PORT = NETWORK_CONSTANTS.DEFAULT_NETWORK_PORT;
export const DEFAULT_DISCOVERY_ENABLED = NETWORK_CONSTANTS.DEFAULT_DISCOVERY_ENABLED;
export const DEFAULT_MAX_CONNECTIONS = NETWORK_CONSTANTS.DEFAULT_MAX_CONNECTIONS;
export const DEFAULT_CONNECTION_TIMEOUT = NETWORK_CONSTANTS.DEFAULT_CONNECTION_TIMEOUT;
export const DEFAULT_CONSCIOUSNESS_LEVEL = CONSCIOUSNESS_CONSTANTS.DEFAULT_CONSCIOUSNESS_LEVEL;
export const DEFAULT_FIELD_STRENGTH = CONSCIOUSNESS_CONSTANTS.DEFAULT_FIELD_STRENGTH;
export const DEFAULT_RESONANCE_SENSITIVITY = CONFIG_CONSTANTS.DEFAULT_RESONANCE_SENSITIVITY;
export const DEFAULT_ALLOW_INCOMING = CONFIG_CONSTANTS.DEFAULT_ALLOW_INCOMING;
export const DEFAULT_REQUIRE_AUTH = CONFIG_CONSTANTS.DEFAULT_REQUIRE_AUTH;
export const DEFAULT_ENCRYPTION_ENABLED = CONFIG_CONSTANTS.DEFAULT_ENCRYPTION_ENABLED;
export const DEFAULT_VORTEX_PRECISION = CONFIG_CONSTANTS.DEFAULT_VORTEX_PRECISION;
export const DEFAULT_TOROIDAL_RESOLUTION = CONFIG_CONSTANTS.DEFAULT_TOROIDAL_RESOLUTION;
export const DEFAULT_GOLDEN_RATIO_PRECISION = CONFIG_CONSTANTS.DEFAULT_GOLDEN_RATIO_PRECISION;
export const DEFAULT_AUTO_UPDATE_RESONANCE = CONFIG_CONSTANTS.DEFAULT_AUTO_UPDATE_RESONANCE;
export const DEFAULT_LOG_LEVEL = CONFIG_CONSTANTS.DEFAULT_LOG_LEVEL;
export const DEFAULT_ENABLE_METAPHYSICAL_INSIGHTS = CONFIG_CONSTANTS.DEFAULT_ENABLE_METAPHYSICAL_INSIGHTS;
export const DEFAULT_TOROIDAL_FLOW_RATE = CONFIG_CONSTANTS.DEFAULT_TOROIDAL_FLOW_RATE;
export const DEFAULT_CONSCIOUSNESS_FIELD_RADIUS = CONSCIOUSNESS_CONSTANTS.DEFAULT_FIELD_RADIUS;
export const TEST_TIMEOUT = CONFIG_CONSTANTS.TEST_TIMEOUT;
export const TEST_COVERAGE_THRESHOLD = CONFIG_CONSTANTS.TEST_COVERAGE_THRESHOLD;
export const TEST_PERFORMANCE_THRESHOLD = CONFIG_CONSTANTS.TEST_PERFORMANCE_THRESHOLD;
export const TEST_MAX_MEMORY_USAGE = CONFIG_CONSTANTS.TEST_MAX_MEMORY_USAGE;
export const UI_OPERATION_MAX_DURATION = CONFIG_CONSTANTS.UI_OPERATION_MAX_DURATION;
export const NETWORK_MESSAGE_MAX_DURATION = CONFIG_CONSTANTS.NETWORK_MESSAGE_MAX_DURATION;
export const SCALABILITY_OPS_PER_SEC = CONFIG_CONSTANTS.SCALABILITY_OPS_PER_SEC;
export const PWA_BASE_SIZE = CONFIG_CONSTANTS.PWA_BASE_SIZE;
export const PWA_BUNDLE_SIZE_OPTIMIZED = CONFIG_CONSTANTS.PWA_BUNDLE_SIZE_OPTIMIZED;
export const PWA_BUNDLE_SIZE_STANDARD = CONFIG_CONSTANTS.PWA_BUNDLE_SIZE_STANDARD;
export const PWA_BUNDLE_SIZE_INCREMENT_VORTEX = CONFIG_CONSTANTS.PWA_BUNDLE_SIZE_INCREMENT_VORTEX;
export const PWA_BUNDLE_SIZE_INCREMENT_PATTERN = CONFIG_CONSTANTS.PWA_BUNDLE_SIZE_INCREMENT_PATTERN;
export const PWA_BUNDLE_SIZE_INCREMENT_OFFLINE = CONFIG_CONSTANTS.PWA_BUNDLE_SIZE_INCREMENT_OFFLINE;
export const PWA_BUNDLE_SIZE_INCREMENT_SYNC = CONFIG_CONSTANTS.PWA_BUNDLE_SIZE_INCREMENT_SYNC;
export const FRACTAL_PRECISION = CONFIG_CONSTANTS.FRACTAL_PRECISION; 