/**
 * Credits and citations, generated. Nobody types a reference again.
 *
 * Three things a reader needs and an author should never hand-maintain:
 *   how to cite THIS work, in the formats people actually paste
 *   the references it cites, as a .bib anyone can drop into a manuscript
 *   who and what it is built on, from the history rather than from memory
 *
 * All of it derives from package.json, CITATION.cff, the prior-art ledger and
 * git. A hand-kept BibTeX entry drifts from the version the moment one is cut,
 * and a hand-kept credits list is pinned to whoever the author remembered —
 * which has been the same defect three times over in this session alone.
 *
 * WHAT IS NOT AUTOMATED, and will not be: deciding that a paper is a relevant
 * citation. research:waves finds candidates by the hundred; whether one is
 * actually related is a judgement, and auto-inserting would fill the ledger
 * with work nobody read. Formatting is mechanical, relevance is not.
 *
 *   npm run citations        write CITATION.bib and the README block
 *   npm run citations:check  fail if either has drifted
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { join } from 'node:path'

const ROOT = join(import.meta.dirname, '..')
const CHECK = process.argv.includes('--check')
const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))
const led = JSON.parse(readFileSync(join(ROOT, 'src/verification/prior-art.json'), 'utf8'))
const ledger = JSON.parse(readFileSync(join(ROOT, 'lean/ledger.json'), 'utf8'))

const YEAR = new Date().getUTCFullYear()
const REPO = pkg.repository.url.replace(/^git\+/, '').replace(/\.git$/, '')
const DOI = led.concept_doi
const AUTHOR = pkg.author.name
const [given, ...family] = AUTHOR.split(' ')
const CFF_TITLE = (readFileSync(join(ROOT, 'CITATION.cff'), 'utf8').match(/^title:\s*(.+)$/m) ?? [, pkg.name])[1].trim()

const refs = Object.values(led.contributions)
  .flatMap((c) => c.priorArt?.citations ?? [])
  .filter((x) => x.resolved === true && x.kind === 'doi' && x.id)
const seen = new Set()
const unique = refs.filter((r) => (seen.has(r.id) ? false : seen.add(r.id)))

const key = (doi) => doi.replace(/[^A-Za-z0-9]/g, '_')
const bib = [
  `% Generated by scripts/citations.mjs — do not edit by hand.`,
  `% This work, then every reference it cites whose DOI resolved to the title shown.`,
  ``,
  `@software{${pkg.name},`,
  `  title    = {${CFF_TITLE}},`,
  `  author   = {${family.join(' ')}, ${given}},`,
  `  year     = {${YEAR}},`,
  `  version  = {${pkg.version}},`,
  `  doi      = {${DOI}},`,
  `  url      = {${pkg.homepage}},`,
  `  note     = {${ledger.proven} of ${ledger.theorems} statements accepted by the Lean 4 kernel},`,
  `}`,
  ``,
  ...unique.flatMap((r) => [
    `@misc{${key(r.id)},`,
    `  title = {${r.resolvedTitle.replace(/[{}]/g, '')}},`,
    `  doi   = {${r.id}},`,
    `  note  = {resolved against Crossref on ${r.resolvedOn}},`,
    `}`,
    ``,
  ]),
].join('\n')

const BEGIN = '<!-- CITE:BEGIN — generated by scripts/citations.mjs; do not edit by hand -->'
const END = '<!-- CITE:END -->'
const block = `${BEGIN}

## How to cite

Cite the **concept DOI**: it resolves to the newest release, where a
per-version DOI goes stale. \`CITATION.bib\` in this repository carries this
entry and every reference below it, generated — you should never need to type
one.

\`\`\`bibtex
@software{${pkg.name},
  title   = {${CFF_TITLE}},
  author  = {${family.join(' ')}, ${given}},
  year    = {${YEAR}},
  version = {${pkg.version}},
  doi     = {${DOI}},
  url     = {${pkg.homepage}},
}
\`\`\`

${family.join(' ')}, ${given[0]}. (${YEAR}). *${CFF_TITLE}* (Version ${pkg.version}) [Computer software]. https://doi.org/${DOI}

### Built on

| | |
| --- | --- |
| proof kernel | Lean 4 — ${ledger.proven} of ${ledger.theorems} statements accepted, dependency sets recorded per theorem |
| reference resolution | Crossref REST API — ${unique.length} DOIs, each re-resolved to the title recorded beside it |
| archive | Zenodo — concept DOI [${DOI}](https://doi.org/${DOI}) |
| licence | ${pkg.license} |

${END}`

const README = join(ROOT, 'README.md')
const readme = readFileSync(README, 'utf8')
const i = readme.indexOf(BEGIN)
let next
if (i < 0) {
  const anchor = readme.indexOf('<!-- VERSION:BEGIN')
  if (anchor < 0) { console.error('citations FAIL — no VERSION block to place the citation block before'); process.exit(1) }
  next = readme.slice(0, anchor) + block + '\n\n' + readme.slice(anchor)
} else {
  next = readme.slice(0, i) + block + readme.slice(readme.indexOf(END, i) + END.length)
}

const BIB = join(ROOT, 'CITATION.bib')
if (CHECK) {
  const problems = []
  let have = ''
  try { have = readFileSync(BIB, 'utf8') } catch { problems.push('CITATION.bib is missing') }
  if (have && have !== bib) problems.push('CITATION.bib is not what the ledger produces')
  if (readme !== next) problems.push('the README citation block is not what the ledger produces')
  if (problems.length) { for (const p of problems) console.error(`  ✗ ${p}`); console.error('citations FAIL — run npm run citations'); process.exit(1) }
  console.log(`citations ok — this work and its ${unique.length} references are the ones the ledger records`)
} else {
  writeFileSync(BIB, bib)
  writeFileSync(README, next)
  console.log(`citations — wrote CITATION.bib (this work + ${unique.length} references) and the README block`)
}
