#!/usr/bin/env node
/**
 * Generate docs/DOCUMENTATION_INDEX.md from the actual docs tree.
 *
 * The hand-maintained index had drifted the way hand-maintained indexes do:
 * three references to CHALLENGE_* files that no longer exist (written as bare
 * text to slip past the dead-link gate), and ~20 real docs — including the
 * flagship computed pages SEQUENCE/KERNEL/AUDIT — missing entirely. This
 * derives the index from the files instead: every docs/*.md is listed with a
 * title and a description mined from its own opening prose, grouped by subject.
 *
 * Two properties fall out for free. Completeness: a new doc appears the next
 * time this runs, and docs:index:check fails until it does. No dead links: every
 * entry points at a file that was just read, and the VitePress build (dead links
 * are fatal) is the second gate. The index can no longer lie about the corpus.
 *
 * Regenerate: npm run docs:index · verify: npm run docs:index:check
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { resolve, dirname, join, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const docsDir = resolve(root, 'docs')
const indexPath = join(docsDir, 'DOCUMENTATION_INDEX.md')

// Not corpus entries: the home page, the site-excluded README, and this index.
// (index.md as a basename also covers docs/pages/index.md, the /pages/ landing.)
const EXCLUDE_BASENAME = new Set(['index.md', 'README.md', 'DOCUMENTATION_INDEX.md'])

/** Every .md under docs/, POSIX-relative to docsDir, excluding build dirs. */
function collect(dir, prefix = '') {
  const out = []
  for (const name of readdirSync(dir).sort()) {
    if (name === '.vitepress' || name === 'node_modules' || name === 'public') continue
    const abs = join(dir, name)
    const rel = prefix ? `${prefix}/${name}` : name
    if (statSync(abs).isDirectory()) out.push(...collect(abs, rel))
    else if (name.endsWith('.md') && !EXCLUDE_BASENAME.has(name)) out.push(rel)
  }
  return out
}

/** First H1 as the title; fall back to a prettified filename. */
function titleOf(text, rel) {
  const m = text.match(/^#\s+(.+?)\s*$/m)
  return m ? m[1].trim() : basename(rel, '.md').replace(/_/g, ' ')
}

/** One-line description mined from the doc's own opening prose. */
function describe(text) {
  const prose = text
    .replace(/^---\n[\s\S]*?\n---\n/, ' ') // frontmatter
    .replace(/```[\s\S]*?```/g, ' ') // fenced code
    .replace(/<!--[\s\S]*?-->/g, ' ') // html comments
    .replace(/<[^>]+>/g, ' ') // html tags
    .replace(/^#{1,6}\s+.*$/gm, ' ') // headings
    .replace(/^\s{0,3}[-*+]\s+/gm, '') // bullet markers
    .replace(/^\s{0,3}\d+\.\s+/gm, '') // ordered markers
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ') // images
    .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1') // links → text
    .replace(/[*_`>|]/g, ' ') // inline markup
    .replace(/\s+/g, ' ')
    .trim()
  if (!prose) return ''
  const limit = 120
  if (prose.length <= limit) return prose
  const slice = prose.slice(0, limit)
  const cut = slice.lastIndexOf(' ')
  return `${(cut > 70 ? slice.slice(0, cut) : slice).trim()}…`
}

// Subject grouping, evaluated in order; the last entry catches the remainder.
// Computed/projected pages come first — they are the site's proof surface.
const isComputed = (rel, base) =>
  rel.startsWith('pages/') ||
  rel.startsWith('0/') ||
  ['SEQUENCE.md', 'KERNEL.md', 'AUDIT.md', 'DIGIT_STREAMS.md', 'A432_QUANTUM_SCAN.md'].includes(base)

const GROUPS = [
  { title: 'Computed census & projections', test: (rel, base) => isComputed(rel, base) },
  { title: 'A432 system', test: (_rel, base) => base.startsWith('A432_') },
  { title: 'Quantum & security', test: (_rel, base) => base.startsWith('QUANTUM_') },
  {
    title: 'Harmonics & solutions',
    test: (_rel, base) => /^(HARMONIC|HARMONIZED|POSSIBILITIES|MULTIPLE_REALITY)/.test(base),
  },
  { title: 'ZeroPoint core', test: (_rel, base) => base.startsWith('ZEROPOINT_') },
  {
    title: 'Trinity · Tesla · 3-6-9',
    test: (_rel, base) => /^(TRINITY|TESLA|369|INFINITE|CONFUSION)/.test(base),
  },
  { title: 'Guides & reference', test: () => true },
]

const files = collect(docsDir).map((rel) => {
  const text = readFileSync(join(docsDir, rel), 'utf8')
  return { rel, base: basename(rel), title: titleOf(text, rel), description: describe(text) }
})

const grouped = GROUPS.map((g) => ({
  title: g.title,
  items: files
    .filter((f) => GROUPS.find((gg) => gg.test(f.rel, f.base)) === g)
    .sort((a, b) => a.rel.localeCompare(b.rel)),
})).filter((g) => g.items.length > 0)

const lines = [
  '<!-- GENERATED by scripts/docs-index.mjs — do not edit by hand -->',
  '',
  '# ZeroPoint Node Documentation Index',
  '',
  `Every Markdown page in \`docs/\` (${files.length} in all), grouped by subject with a`,
  'description mined from the page itself. This file is generated — a new doc appears',
  'here on `npm run docs:index`, and `npm run docs:index:check` fails until it does, so',
  'the index can neither miss a page nor point at one that no longer exists.',
  '',
]
for (const g of grouped) {
  lines.push(`## ${g.title}`, '')
  for (const f of g.items) {
    lines.push(`- [${f.title}](${f.rel})${f.description ? ` — ${f.description}` : ''}`)
  }
  lines.push('')
}
lines.push('Regenerate: `npm run docs:index` · verify: `npm run docs:index:check`', '')

const next = lines.join('\n')

if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = readFileSync(indexPath, 'utf8')
  } catch {
    console.error('docs/DOCUMENTATION_INDEX.md missing — run npm run docs:index')
    process.exit(1)
  }
  if (current !== next) {
    console.error('DOCUMENTATION_INDEX.md drift — run npm run docs:index')
    process.exit(1)
  }
  console.log('docs:index:check ok', files.length, 'docs')
  process.exit(0)
}

writeFileSync(indexPath, next)
console.log('wrote docs/DOCUMENTATION_INDEX.md', files.length, 'docs in', grouped.length, 'groups')
