#!/usr/bin/env node
/**
 * Generate static doc projections from the kernel (Wave 6).
 * Pages are projections of src/0 — not second sources.
 */

import { mkdirSync, writeFileSync, readFileSync, existsSync, readdirSync } from 'node:fs'
import { resolve, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  KERNEL_SEALED,
  VORTEX_SEQUENCE,
  VORTEX_REVERSE,
  throughVoid,
  developmentVortex,
  foldVortex,
  foldVortexReflection,
  vortexStrokeGateways,
  decodeVortexDashAngles,
  WAVE_CHAIN,
} from '../src/0/index.ts'
import { computeContentUuid } from '../src/integrity/content-uuid.ts'
import { importExportGraphTip } from '../src/kernel/import-graph.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = resolve(root, 'docs/pages')

const stroke = vortexStrokeGateways()
const vortex = foldVortex()
const reflection = foldVortexReflection()
const dash = decodeVortexDashAngles()
const dv = developmentVortex('verify')
const graph = importExportGraphTip()

const pages = [
  {
    slug: 'origin',
    title: 'Origin',
    body: [
      'Dependency-free leaf `src/0`. Fold = identity.',
      `KERNEL_SEALED: **${KERNEL_SEALED}**`,
      'Boundary: exact fold math; refused Clay/FTL/Payload.',
    ].join('\n\n'),
  },
  {
    slug: 'vortex-stroke',
    title: 'Vortex stroke',
    body: [
      `Sequence: \`${VORTEX_SEQUENCE.join('·')}\``,
      `Written: \`${stroke.written}\``,
      `Gateways: \`[${stroke.gateways.join(', ')}]\``,
      `foldVortex.valid: **${vortex.valid}**`,
      `Dash vortexMatches: **${dash.vortexMatches}** · weightedBearing: **${dash.weightedBearing}**`,
    ].join('\n\n'),
  },
  {
    slug: 'content-uuid',
    title: 'Content-uuid',
    body: [
      'JCS → SHA-256 → uuidv8 (`src/integrity/content-uuid.ts`).',
      'FNV `toUuid` stays for cheap folds; SHA seals proofs.',
      'Verify on read — mismatch is tamper.',
    ].join('\n\n'),
  },
  {
    slug: 'sequence-dual',
    title: 'Sequence dual',
    body: [
      `Kernel spine: \`${VORTEX_SEQUENCE.join('')}\` + void 0 · \`digitalRoot(0)→9\`.`,
      'Legacy path: `03691248751` · VBM `digitalRoot(0)→0` via adapters.',
      'One structure, read twice — both lines computed, never typed:',
      [
        '```',
        `forward     ${reflection.strokeForward}        ${reflection.forward.join('')}`,
        `reflected   ${reflection.strokeReflected}        ${reflection.reflected.join('')}`,
        '```',
      ].join('\n'),
      `The void tail reflects: \`0\` is fixed, the trailing unit is not — \`0\\1\` becomes \`0\\${throughVoid(1)}\`.`,
      `Mirror \`throughVoid(n) = 1 − n mod 9\` — involution fixed only at ${reflection.fixedPoints.join(',')}; every pair sums to 10.`,
      `Not array reversal (\`${VORTEX_REVERSE.join('')}\`): reversal reorders, the mirror re-values.`,
      `Entangled: doubling covers the orbit and its gap is exactly \`${reflection.gap.join(',')}\` · \`D∘M∘D⁻¹∘M = x+1\` · \`|⟨D,M⟩| = ${reflection.groupOrder}\` against \`${reflection.separateProduct}\` apart (excess ${reflection.excess}).`,
      `foldVortexReflection().valid: **${reflection.valid}**`,
      'See [SEQUENCE.md](../SEQUENCE.md).',
    ].join('\n\n'),
  },
  {
    slug: 'development-vortex',
    title: 'Development vortex',
    body: [
      `Wave chain: ${WAVE_CHAIN.join(' → ')}`,
      `developmentVortex(verify).computes: **${dv.computes}**`,
      `Throat merged: \`${dv.throat.merged}\``,
      `Import graph: files=${graph.fileCount} edges=${graph.edgeCount}`,
      'Lobe L = ceccec.github.io · Lobe R = erpax · Throat = src/0.',
    ].join('\n\n'),
  },
]

const indexLines = [
  '<!-- GENERATED by scripts/docs-pages.mjs — do not edit by hand -->',
  '',
  '# Computed pages',
  '',
  'Projections of `src/0` / integrity / kernel — not second sources.',
  '',
  ...pages.map((p) => `- [${p.title}](./${p.slug}.md)`),
  '',
]

/**
 * Per-page receipt — content-addressed over the page's own title + body.
 * Computed before embedding, so the stamp attests to what the page says.
 * A set-level receipt over slugs alone cannot: it never moves when a body moves.
 */
function receiptOf(p) {
  return computeContentUuid({ kind: 'docs-page', slug: p.slug, title: p.title, body: p.body })
}

/** Set root — folds every page receipt, so any body change moves it. */
const receipt = computeContentUuid({
  kind: 'docs-pages',
  pages: pages.map((p) => ({ slug: p.slug, receipt: receiptOf(p) })),
  stroke: stroke.written,
  vortexValid: vortex.valid,
  graphRoot: graph.root,
})

function renderPage(p) {
  return [
    '<!-- GENERATED by scripts/docs-pages.mjs — do not edit by hand -->',
    '',
    `# ${p.title}`,
    '',
    p.body,
    '',
    `Receipt: \`${receiptOf(p)}\` · set \`${receipt}\``,
    '',
  ].join('\n')
}

if (process.argv.includes('--check')) {
  if (!existsSync(outDir)) {
    console.error('docs/pages missing — run npm run docs:pages')
    process.exit(1)
  }
  const existing = readdirSync(outDir).filter((f) => f.endsWith('.md')).sort()
  const expected = ['index.md', ...pages.map((p) => `${p.slug}.md`)].sort()
  if (existing.join() !== expected.join()) {
    console.error('docs/pages drift (file set) — run npm run docs:pages')
    process.exit(1)
  }
  for (const p of pages) {
    const path = join(outDir, `${p.slug}.md`)
    if (readFileSync(path, 'utf8') !== renderPage(p)) {
      console.error(`docs/pages/${p.slug}.md drift — run npm run docs:pages`)
      process.exit(1)
    }
  }
  const idx = join(outDir, 'index.md')
  if (readFileSync(idx, 'utf8') !== indexLines.join('\n') + `Receipt: \`${receipt}\`\n`) {
    console.error('docs/pages/index.md drift — run npm run docs:pages')
    process.exit(1)
  }
  console.log('docs:pages:check ok', receipt)
  process.exit(0)
}

mkdirSync(outDir, { recursive: true })
for (const p of pages) {
  writeFileSync(join(outDir, `${p.slug}.md`), renderPage(p))
}
writeFileSync(join(outDir, 'index.md'), indexLines.join('\n') + `Receipt: \`${receipt}\`\n`)
console.log('wrote docs/pages', pages.length, receipt)
