/**
 * Put the census in the README, where the most readers are.
 *
 * The paper's abstract was corrected to open with how much of this package any
 * law actually holds. The README was not, and the README is what GitHub and npm
 * show — far more people read it than will ever open the paper. It opened with
 * "computes both rather than asserting them", which is true and is the
 * flattering half, and said nothing about the four fifths that no law touches.
 *
 * A peer session found the same shape in their own corpus: honesty per-item,
 * claim at the door. The rule gets stated at the level of the item and broken at
 * the level of the summary, and the summary is what a reader meets.
 *
 * Generated, so it cannot drift from the measurement it reports.
 *
 *   npm run readme:census        rewrite the block
 *   npm run readme:census --check  fail if it has drifted
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = join(import.meta.dirname, '..')
const README = join(ROOT, 'README.md')
const CHECK = process.argv.includes('--check')
const J = (p) => JSON.parse(readFileSync(join(ROOT, p), 'utf8'))

const c = J('src/verification/constrained.json')
const pin = J('src/verification/seal-pinning.json')
const led = J('lean/ledger.json')
const ax = J('src/verification/axiom-index.json')

const BEGIN = '<!-- CENSUS:BEGIN — generated by scripts/readme-census.mjs; do not edit by hand -->'
const END = '<!-- CENSUS:END -->'

const block = `${BEGIN}

## How much of this a law actually holds

These are measured by experiment on every run, not asserted. Each number has a
gate that re-performs the measurement and fails if this block disagrees with it.

| | |
| --- | --- |
| exported values reachable from no law at all | **${c.reachability.unreachable} of ${c.reachability.exportedValues}** |
| exported literal constants held by nothing | **${c.literalCensus.free} of ${c.literalCensus.perturbable}** |
| constants forced by at least one law | ${c.literalCensus.forced} |
| seal predicates that are *pinned* rather than forced | ${pin.tally.pinned ?? 0} of ${Object.keys(pin.seals).length} |
| Lean statements the kernel accepts | ${led.proven} of ${led.theorems} |
| of those, resting on **no axioms at all** | ${ax.totals.restingOnNothingAtAll} |

The first row is the one that matters and it is a **floor**: the reachability
closure over-approximates, so at least that many are outside everything this
package can check. A *pinned* predicate holds an expected value as a literal, so
it falls for a convention as readily as for a law — useful against drift, and
not evidence that anything derives the value.

Novelty is claimed nowhere. It is a universal negative that no finite search
decides, and the ledger has no status that would permit it; what a dated deposit
establishes is priority. See \`npm run constrained\`, \`npm run seal:pinning\`,
\`npm run axiom:index\`.

${END}`

const readme = readFileSync(README, 'utf8')
const i = readme.indexOf(BEGIN)
let next
if (i < 0) {
  // First run: place it directly after the opening claim, which is the sentence
  // it exists to qualify.
  const anchor = '## What this is for'
  const at = readme.indexOf(anchor)
  if (at < 0) { console.error('readme:census FAIL — cannot find "## What this is for" to place the block before'); process.exit(1) }
  next = readme.slice(0, at) + block + '\n\n' + readme.slice(at)
} else {
  const j = readme.indexOf(END, i) + END.length
  next = readme.slice(0, i) + block + readme.slice(j)
}

if (CHECK) {
  if (readme !== next) { console.error('readme:census FAIL — the README census block is not what the measurements say; run npm run readme:census'); process.exit(1) }
  console.log('readme:census ok — the block is the measurement')
} else {
  writeFileSync(README, next)
  console.log(`readme:census — ${c.reachability.unreachable}/${c.reachability.exportedValues} unreachable, ${c.literalCensus.free}/${c.literalCensus.perturbable} constants held by nothing, ${pin.tally.pinned} pinned, ${ax.totals.restingOnNothingAtAll} theorems on no axioms`)
}
