#!/usr/bin/env node
/**
 * Generate docs/KERNEL.md from live kernel census. Drift fails closed via readme:check.
 */

import { writeFileSync, readFileSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  KERNEL_SEALED,
  VORTEX_SEQUENCE,
  developmentVortex,
  foldVortex,
  vortexStrokeGateways,
  WAVE_CHAIN,
} from '../src/0/index.ts'
import {
  runDevelopmentVortexAll,
  importExportGraphTip,
  auditTip,
  foldA432AuditCensus,
  nextSelfDevelopTip,
} from '../src/kernel/index.ts'
import { computeContentUuid } from '../src/integrity/content-uuid.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const outPath = resolve(root, 'docs/KERNEL.md')
const auditPath = resolve(root, 'docs/AUDIT.md')

const stroke = vortexStrokeGateways()
const vortex = foldVortex()
const all = runDevelopmentVortexAll()
const dv = developmentVortex('verify')
const graph = importExportGraphTip()
const tip = auditTip()
const audit = foldA432AuditCensus()
const selfTip = nextSelfDevelopTip()

const body = `<!-- GENERATED by scripts/readme-gen.mjs — do not edit by hand. Run: npm run readme -->

# Kernel census

- KERNEL_SEALED: **${KERNEL_SEALED}**
- VORTEX_SEQUENCE: \`${VORTEX_SEQUENCE.join('·')}\`
- Stroke: \`${stroke.written}\`
- Gateways: \`[${stroke.gateways.join(', ')}]\`
- foldVortex.valid: **${vortex.valid}**
- developmentVortex(verify).computes: **${dv.computes}**
- runDevelopmentVortexAll().ok: **${all.ok}**
- corpus root: \`${all.root}\`
- a432 import/export graph: **${graph.computes}** · files=${graph.fileCount} · edges=${graph.edgeCount} · exports=${graph.exportCount}
- graph root: \`${graph.root}\`
- audit: forks=${tip.forkCount} · ambient Math hits=${tip.mathCount ?? 0} · randomUUID=${tip.randomCount} · root=\`${tip.root}\`
- **self-develop tip:** ${selfTip.stalled ? 'STALLED' : 'idle'} · \`${selfTip.kind}\` · ${selfTip.path}${selfTip.line ? ':' + selfTip.line : ''}
- tip action: ${selfTip.action}
- claySolved: **${graph.claySolved}** · physicalFtl: **${graph.physicalFtl}**

## Law

If development stops, gaps in self-development exist. Run \`npm run self:next\` (computed from audit — not a hand checklist).

## Double-torus development

Lobe L = ceccec.github.io · Lobe R = erpax · Throat = \`src/0\` foldPair.

Wave chain: ${WAVE_CHAIN.join(' → ')}.

## Self-reference

Import/export census is computed (\`foldA432ImportExportGraph\`) — content-uuid + merkleFold, not a hand inventory. FTL = memoByRoot / one merkle walk. Audit census: \`foldA432AuditCensus\` (see [AUDIT.md](./AUDIT.md)). Next tip: \`planTrinity\` / \`nextSelfDevelopTip\`.

## Honesty

Exact: fold, digital root, vortex stroke, import graph fold, audit census, plan trinity. Faithful: torus geometry. Refused: Clay solved, physical FTL, Payload/ERP port.
`

const contentUuid = computeContentUuid({ kind: 'kernel-census', root: all.root, sealed: KERNEL_SEALED })
const stamped = body + `\nReceipt content-uuid: \`${contentUuid}\`\n`

const forkLines = audit.digitalRootForks
  .slice(0, 40)
  .map((h) => `- \`${h.path}:${h.line}\``)
  .join('\n')
const pct9Lines = audit.pct9Roots
  .slice(0, 40)
  .map((h) => `- \`${h.path}:${h.line}\``)
  .join('\n')
const randLines = audit.mathBanSites
  .slice(0, 40)
  .map((h) => `- \`${h.path}:${h.line}\``)
  .join('\n')

const auditBody = `<!-- GENERATED by scripts/readme-gen.mjs — do not edit by hand. Run: npm run readme -->

# A432 audit census (Wave 14)

Computed by \`foldA432AuditCensus\` — not a hand inventory.

- files scanned: **${audit.fileCount}** (.ts + .html)
- digitalRoot named forks: **${audit.digitalRootForks.length}**
- %9 root inlines: **${audit.pct9Count}**
- ambient Math.* hits: **${audit.mathCount}**
- randomUUID sites: **${audit.randomCount}**
- neither roots nor algebra (direct): **${audit.neitherDirect}**
- digitalRoot via math/core (harmonic alias): **${audit.harmonicAliasImporters}**
- root: \`${audit.root}\`
- content-uuid: \`${audit.contentUuid}\`
- claySolved: **0** · physicalFtl: **0**

## digitalRoot named forks (sample ≤40)

${forkLines || '_none_'}

## %9 root inlines (sample ≤40)

${pct9Lines || '_none_'}

## ambient Math.* hits (sample ≤40)

${randLines || '_none_'}

## Algebra-only law

No ambient \`Math.*\` under \`src/\` (.ts+.html) — use \`src/0/algebra\` / HTML bootstrap. \`npm run math:ban\` fails closed.

## Structural debt

\`a432.math\` still exports \`harmonicRoot12 as digitalRoot\` — same name, different spine than \`legacyDigitalRoot\`. Files importing \`digitalRoot\` from \`a432.core\`/\`a432.math\` are alias debt until renamed or rebound.
`

if (process.argv.includes('--check')) {
  if (!existsSync(outPath) || !existsSync(auditPath)) {
    console.error('docs/KERNEL.md or docs/AUDIT.md missing — run npm run readme')
    process.exit(1)
  }
  if (readFileSync(outPath, 'utf8') !== stamped) {
    console.error('docs/KERNEL.md drift — run npm run readme')
    process.exit(1)
  }
  if (readFileSync(auditPath, 'utf8') !== auditBody) {
    console.error('docs/AUDIT.md drift — run npm run readme')
    process.exit(1)
  }
  console.log('readme:check ok')
  process.exit(0)
}

writeFileSync(outPath, stamped)
writeFileSync(auditPath, auditBody)
console.log('wrote docs/KERNEL.md', contentUuid)
console.log('wrote docs/AUDIT.md', audit.contentUuid)
