#!/usr/bin/env node
/**
 * Generate the README spectrum block from the live kernel + a432 mappings.
 * Facts are computed, never typed — drift fails closed via spectrum:check.
 *
 * Only the region between SPECTRUM:BEGIN / SPECTRUM:END is owned by this
 * script; the rest of README.md stays hand-written.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  VORTEX_ORBIT,
  VORTEX_AXIS,
  throughVoid,
  decodeVortexDashAngles,
  vortexStrokeGateways,
} from '../src/0/index.ts'
import {
  digitAngleToCMYK,
  vortexColor,
  CMYK_FREQUENCIES,
  CMYK_FREQUENCY_RATIOS,
} from '../src/0/3/6/9/1/2/4/8/7/5/1/a432.cmyk.ts'
import { frequencyForDigit, hueForDigit } from '../src/0/3/6/9/1/2/4/8/7/5/1/a432.math.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const readmePath = resolve(root, 'README.md')
const BEGIN = '<!-- SPECTRUM:BEGIN — generated by scripts/spectrum-gen.mjs; do not edit by hand -->'
const END = '<!-- SPECTRUM:END -->'

const dash = decodeVortexDashAngles()
const stroke = vortexStrokeGateways()
const gateways = new Set(stroke.gateways)
const steps = new Map(dash.steps.map((s) => [s.step, s]))
const order = [...VORTEX_ORBIT, ...VORTEX_AXIS]

/** Pitch is defined on the trinity axis only — off-axis it throws by design. */
function hzOf(d) {
  try {
    return frequencyForDigit(d)
  } catch {
    return null
  }
}

const rows = order.map((d, i) => {
  const s = steps.get(i)
  const cmyk = digitAngleToCMYK(d, 0)
  return {
    d,
    mirror: throughVoid(d),
    polarity: s.dash === '/' ? '+' : '−',
    delta: s.angleDelta,
    bearing: s.bearing,
    hue: hueForDigit(d),
    cmyk: `${cmyk.c}/${cmyk.m}/${cmyk.y}/${cmyk.k}`,
    swatch: vortexColor(d),
    hz: hzOf(d),
    gateway: gateways.has(d),
  }
})

// Colour class degeneracy — vortexColor depends only on d mod 3.
const classes = new Map()
for (const r of rows) {
  if (!classes.has(r.swatch)) classes.set(r.swatch, [])
  classes.get(r.swatch).push(r.d)
}
const classLines = [...classes.entries()]
  .map(([hex, ds]) => `\`${hex}\` → \`{${ds.join(', ')}}\``)
  .join(' · ')

const axisHz = VORTEX_AXIS.map((d) => `${d}→**${hzOf(d)}** Hz`).join(' · ')
const axisHzInteger = VORTEX_AXIS.every((d) => Number.isInteger(hzOf(d)))
const offAxis = VORTEX_ORBIT.filter((d) => hzOf(d) === null)
const nonIntegerFreqs = Object.entries(CMYK_FREQUENCIES).filter(([, v]) => !Number.isInteger(v))
// Exactness is a claim about representation: the ratios stay integral, the
// float collapse does not. Proven rather than asserted — accumulate and compare.
const ratiosIntegral = Object.values(CMYK_FREQUENCY_RATIOS).every(
  (f) => Number.isInteger(f.numerator) && Number.isInteger(f.denominator),
)
const leakChannel = nonIntegerFreqs[0]?.[0]
const leakRatio = leakChannel ? CMYK_FREQUENCY_RATIOS[leakChannel] : null
let floatSum = 0
let exactNum = 0
if (leakRatio) {
  for (let i = 0; i < 10; i += 1) {
    floatSum += CMYK_FREQUENCIES[leakChannel]
    exactNum += leakRatio.numerator
  }
}
const exactSum = leakRatio ? exactNum / leakRatio.denominator : 0
const floatLeaks = leakRatio ? floatSum !== exactSum : false
// hue(d) and freq(d) coincide numerically wherever both are defined.
const hueEqualsHz = VORTEX_AXIS.every((d) => hueForDigit(d) === hzOf(d))

const table = [
  '| d | M(d) | pol | Δ° | bearing | hue° | C/M/Y/K | class | Hz | |',
  '| --: | --: | :-: | --: | --: | --: | --- | --- | --: | --- |',
  ...rows.map(
    (r) =>
      `| ${r.d} | ${r.mirror} | ${r.polarity} | ${r.delta > 0 ? '+' : '−'}${Math.abs(r.delta)} | ${r.bearing} | ${r.hue} | ${r.cmyk} | \`${r.swatch}\` | ${r.hz === null ? '—' : `**${r.hz}**`} | ${r.gateway ? '**gateway**' : ''} |`,
  ),
].join('\n')

const block = `${BEGIN}

Every column below is **computed**, and each carries a different epistemic weight. Read the status ledger before the table, so a defined mapping is never mistaken for a derived law.

| column | source | status |
| --- | --- | --- |
| mirror \`M(d)\` | \`throughVoid\` | **derived** — \`1 − n mod 9\` over (ℤ/9ℤ) |
| polarity, Δ°, bearing | \`decodeVortexDashAngles()\` | **derived** — \`\\\` = −60°, \`/\` = +60°; weighted bearing closes at ${dash.weightedBearing} |
| gateway | \`vortexStrokeGateways()\` | **derived** — polarity reversals \`[${stroke.gateways.join(', ')}]\` |
| hue° | \`hueForDigit\` / \`digitAngleToCMYK\` | **defined** — \`hue = 36d\`, a chosen decagon partition |
| C/M/Y/K | \`digitAngleToCMYK\` | **defined** — HSV→RGB→CMYK of that hue |
| class | \`vortexColor\` | **derived, degenerate** — see note |
| Hz | \`frequencyForDigit\` | **defined on the axis only** — \`432·d/12\`; throws off-axis |

${table}

**Angle and polarity.** Each dash is a ±${Math.abs(rows[0].delta)}° (π/3) step. The *weighted* bearing — \`Σ sign·digit·60°\` — returns to **${dash.weightedBearing} mod 360**, which is what \`closes: ${dash.closes}\` reports. Polarity reverses at exactly ${stroke.gateways.length} digits, \`[${stroke.gateways.join(', ')}]\`, and those reversals are the gateways; they are computed from the stroke, not enumerated by hand.

**Colour ↔ sound: one integer, two units.** ${hueEqualsHz ? 'For the axis, `hue(d) = 36d` degrees and `freq(d) = 432·d/12 = 36d` Hz — the two columns hold the same integer' : 'The hue and frequency columns do not coincide'}: ${VORTEX_AXIS.map((d) => `${d}→${hueForDigit(d)}`).join(', ')} in *both*. This is an **identity of the two definitions**, not an empirical discovery — both reduce to \`36d\`. Stated plainly because it is the kind of correspondence that invites overclaiming.

**Sound is axis-only, by construction.** \`frequencyForDigit\` throws for \`{${offAxis.join(', ')}}\` — it is defined solely on the trinity axis \`{${VORTEX_AXIS.join(', ')}}\`, where \`432·d/12\` yields ${axisHzInteger ? 'exact integers' : 'non-integers'}: ${axisHz}. The flow ring has **no** defined pitch. This mirrors the arithmetic: the axis governs off the flow ring.

**The colour class is degenerate — ${classes.size} values, not ${rows.length}.** \`vortexColor(d)\` computes \`(dr(3d), dr(6d), dr(9d))\`, which depends only on \`d mod 3\`. It therefore partitions the digits into exactly ${classes.size} residue classes: ${classLines}. The axis renders white because \`dr(3d)=dr(6d)=dr(9d)=9\` there. ${rows.length} digits do **not** get ${rows.length} colours — use \`digitAngleToCMYK\` when a per-digit colour is required.

Regenerate: \`npm run spectrum\` · verify: \`npm run spectrum:check\`
${END}`

const readme = readFileSync(readmePath, 'utf8')
const start = readme.indexOf(BEGIN)
const stop = readme.indexOf(END)
if (start === -1 || stop === -1) {
  console.error('README.md missing SPECTRUM markers — cannot place generated block')
  process.exit(1)
}
const next = readme.slice(0, start) + block + readme.slice(stop + END.length)

if (process.argv.includes('--check')) {
  if (readme !== next) {
    console.error('README.md spectrum drift — run npm run spectrum')
    process.exit(1)
  }
  console.log('spectrum:check ok')
  process.exit(0)
}

writeFileSync(readmePath, next)
console.log('wrote README.md spectrum block', rows.length, 'digits')
