#!/usr/bin/env node
/**
 * The four surfaces this package presents, and what each one is missing.
 *
 * A library, a CLI, an MCP server and a documentation site are four front ends
 * onto one body of work, and they drift apart silently because nothing compares
 * them. Measured here rather than asserted: 24 npm entry points, 11 MCP tools,
 * one bin that only starts the server, 190 built pages — and NOT ONE PAGE named
 * a single MCP tool, which is the surface an agent reaches first.
 *
 * WHAT IS GENERATED AND WHY. The MCP page is written from the server's own
 * TOOLS array, never by hand. A hand-written list of eleven tools is a copy,
 * and this repository has spent a day finding out what copies do — the seals
 * that held private gate matrices, the version literal that drifted five
 * minors, the deposit count that stayed at 50 in prose. One source, one page.
 *
 * WHAT IS NOT CLAIMED. Parity of FUNCTIONALITY is not asserted here and could
 * not be: the library exposes 354 quantum functions and the MCP exposes 11
 * tools, and that gap is a design choice about what an agent should reach for,
 * not a defect. What is checked is that nothing a surface OFFERS goes
 * undocumented, which is the part that silently rots.
 *
 *   npm run parity          regenerate the MCP page
 *   npm run parity:check    fail if it has drifted from the server
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = new URL('..', import.meta.url).pathname
// NOT under docs/pages/. That directory is generated by docs-pages.mjs, which
// compares the whole FILE SET against its own list — so a second generator
// writing there reads as drift, correctly. One directory, one owner.
const PAGE = join(ROOT, 'docs/mcp-tools.md')
const CHECK = process.argv.includes('--check')

const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))
const server = readFileSync(join(ROOT, 'src/mcp/server.ts'), 'utf8')

// The tools, read from the server rather than listed. Name and description are
// what a client is actually shown.
const tools = []
for (const m of server.matchAll(/name: '(zeropoint\.\w+)',\s*\n\s*description:\s*([\s\S]*?),\s*\n\s*inputSchema/g)) {
  const description = m[2]
    .split('\n').map((l) => l.trim().replace(/^\+\s*/, ''))
    .join(' ')
    .replace(/^'|'$/g, '')
    .replace(/'\s*'/g, '')
    .trim()
  tools.push({ name: m[1], description })
}
if (tools.length === 0) {
  console.error('parity FAIL — read 0 tools from src/mcp/server.ts, so this proves nothing about the page')
  process.exit(1)
}

const entryPoints = Object.keys(pkg.exports ?? {}).filter((k) => k !== './package.json')
const bins = Object.keys(pkg.bin ?? {})

const page = `# MCP tools

> Generated from \`src/mcp/server.ts\` by \`npm run parity\`. The server is the
> only source; this page is never edited by hand, because a hand-written copy of
> a tool list drifts and nothing notices.

This package ships an MCP server as the bin \`${bins.join('`, `')}\`, exposing
${tools.length} tools. It is the surface an agent reaches first, and until this page
existed it was documented nowhere on the site.

\`\`\`bash
npx ${bins[0]}
\`\`\`

| tool | what it answers |
| --- | --- |
${tools.map((t) => `| \`${t.name}\` | ${t.description.replace(/\|/g, '\\|')} |`).join('\n')}

## The same work through the library

The ${entryPoints.length} importable entry points cover far more than the ${tools.length} tools do —
the tools are a deliberate selection of what an agent should reach for, not the
whole surface. Nothing here claims the two are equivalent.

${entryPoints.map((e) => `- \`zeropoint-node${e === '.' ? '' : e.slice(1)}\``).join('\n')}

## Claims and how to disagree with them

Every claim this package makes carries the command that computes against it:

\`\`\`bash
npm run refute
\`\`\`
`

if (CHECK) {
  if (!existsSync(PAGE)) {
    console.error(`parity:check FAIL — ${PAGE} is missing; run npm run parity`)
    process.exit(1)
  }
  if (readFileSync(PAGE, 'utf8') !== page) {
    console.error('parity:check FAIL — docs/mcp-tools.md has drifted from src/mcp/server.ts; run npm run parity')
    process.exit(1)
  }
  console.log(`parity:check ok — ${tools.length} MCP tools, ${entryPoints.length} entry points, ${bins.length} bin; the page matches the server`)
  process.exit(0)
}

writeFileSync(PAGE, page)
console.log(`parity — ${tools.length} MCP tools written to docs/mcp-tools.md from src/mcp/server.ts`)
console.log(`         ${entryPoints.length} npm entry points and ${bins.length} bin cross-linked from the same page`)
console.log('         the library is deliberately wider than the tool set; that is stated, not hidden')
