#!/usr/bin/env node
/**
 * Version-seal self-test — proves the gate can FAIL.
 *
 * A gate that cannot fail gates nothing (the ratchet counts exactly that as a
 * surface: "boolean claims that cannot be false"). Each case builds a scratch
 * tree, breaks ONE version surface, and requires `--check` to exit non-zero
 * naming that surface. The last case requires a correct tree to exit zero, so
 * the failures are not just a script that always fails.
 *
 *   node scripts/version-seal.test.mjs
 */

import { mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'

const SEAL = resolve(dirname(fileURLToPath(import.meta.url)), 'version-seal.mjs')

const BEGIN = '<!-- VERSION:BEGIN — generated by scripts/version-seal.mjs; do not edit by hand -->'
const END = '<!-- VERSION:END -->'
const STUB = '_Unreleased — replace this line with the notes for this version._'

/** A tree that passes, with the named parts overridden. */
function tree({ version = '2.0.0', cff = '2.0.0', readme = '2.0.0', changelog = null } = {}) {
  const dir = mkdtempSync(join(tmpdir(), 'version-seal-'))
  writeFileSync(
    join(dir, 'package.json'),
    JSON.stringify(
      { name: 'zeropoint-node', version, repository: { url: 'git+https://github.com/ceccec/zeropoint-node.git' } },
      null,
      2
    )
  )
  writeFileSync(join(dir, 'CITATION.cff'), `title: t\nversion: ${cff}\nlicense: x\n`)
  writeFileSync(
    join(dir, 'README.md'),
    [
      '## Publish',
      '',
      BEGIN,
      '',
      `Package: **\`zeropoint-node@${readme}\`** · owner \`ceccec\` · git tag \`v${readme}\``,
      '',
      'npm rejects republishing a version that already exists, so every release is a',
      'new number. Bump with `npm version patch|minor|major`: that reseals CITATION.cff',
      'and this block, opens a CHANGELOG heading, and creates the matching `v*` tag.',
      '',
      END,
      '',
    ].join('\n')
  )
  writeFileSync(join(dir, 'CHANGELOG.md'), changelog ?? `# Changelog\n\n## ${version}\n\nReal notes.\n`)
  return dir
}

/** Run --check against a scratch tree. Returns {code, out}. */
function check(dir) {
  try {
    const out = execFileSync('node', [SEAL, '--check'], {
      encoding: 'utf8',
      env: { ...process.env, VERSION_SEAL_ROOT: dir },
      stdio: ['ignore', 'pipe', 'pipe'],
    })
    return { code: 0, out }
  } catch (err) {
    return { code: err.status ?? 1, out: (err.stdout ?? '') + (err.stderr ?? '') }
  }
}

/** Turn a scratch tree into a git repo with one commit tagged `tag`. */
function tagAs(dir, tag) {
  const git = (...a) =>
    execFileSync('git', ['-c', 'user.email=t@t', '-c', 'user.name=t', ...a], {
      cwd: dir,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    })
  git('init', '-q')
  git('add', '-A')
  git('commit', '-q', '-m', 'seed')
  git('tag', tag)
  return dir
}

const cases = [
  {
    name: 'CITATION.cff drift fails',
    dir: () => tree({ version: '2.0.0', cff: '1.9.0' }),
    wantCode: 1,
    wantText: 'CITATION.cff version is 1.9.0',
  },
  {
    name: 'stale README block fails',
    dir: () => tree({ version: '2.0.0', readme: '1.9.0' }),
    wantCode: 1,
    wantText: 'README.md VERSION block is stale',
  },
  {
    name: 'missing README block fails',
    dir: () => {
      const d = tree({})
      writeFileSync(join(d, 'README.md'), '## Publish\n\nno block here\n')
      return d
    },
    wantCode: 1,
    wantText: 'no VERSION:BEGIN/END block',
  },
  {
    name: 'missing CHANGELOG heading fails',
    dir: () => tree({ version: '2.0.0', changelog: '# Changelog\n\n## 1.9.0\n\nOld notes.\n' }),
    wantCode: 1,
    wantText: 'no `## 2.0.0` heading',
  },
  {
    name: 'unfilled CHANGELOG stub fails',
    dir: () => tree({ version: '2.0.0', changelog: `# Changelog\n\n## 2.0.0\n\n${STUB}\n` }),
    wantCode: 1,
    wantText: 'still the placeholder stub',
  },
  {
    name: 'version below a CHANGELOG heading fails',
    dir: () =>
      tree({
        version: '2.0.0',
        cff: '2.0.0',
        readme: '2.0.0',
        changelog: '# Changelog\n\n## 3.0.0\n\nNewer.\n\n## 2.0.0\n\nReal notes.\n',
      }),
    wantCode: 1,
    wantText: 'is below CHANGELOG heading 3.0.0',
  },
  {
    name: 'non-semver version fails',
    dir: () => tree({ version: 'v2', cff: 'v2', readme: 'v2', changelog: '# Changelog\n\n## 1.0.0\n\nx\n' }),
    wantCode: 1,
    wantText: 'is not semver',
  },
  {
    name: 'version below an existing git tag fails',
    dir: () => {
      // Tag v3.0.0 exists; the tree claims 2.0.0 — a backwards release.
      const d = tree({ version: '3.0.0', cff: '3.0.0', readme: '3.0.0' })
      tagAs(d, 'v3.0.0')
      const pkg = JSON.parse(readFileSync(join(d, 'package.json'), 'utf8'))
      pkg.version = '2.0.0'
      writeFileSync(join(d, 'package.json'), JSON.stringify(pkg, null, 2))
      writeFileSync(join(d, 'CITATION.cff'), 'title: t\nversion: 2.0.0\nlicense: x\n')
      writeFileSync(
        join(d, 'README.md'),
        readFileSync(join(d, 'README.md'), 'utf8').replaceAll('3.0.0', '2.0.0')
      )
      writeFileSync(join(d, 'CHANGELOG.md'), '# Changelog\n\n## 2.0.0\n\nReal notes.\n')
      return d
    },
    wantCode: 1,
    wantText: 'is below released tag v3.0.0',
  },
  {
    name: 'a tag naming a different package.json version fails',
    dir: () => {
      // Tag v2.0.0 was cut at 1.9.0 — a mis-cut tag the publish job would trust.
      const d = tree({ version: '1.9.0', cff: '1.9.0', readme: '1.9.0', changelog: '# Changelog\n\n## 1.9.0\n\nx\n' })
      tagAs(d, 'v2.0.0')
      const pkg = JSON.parse(readFileSync(join(d, 'package.json'), 'utf8'))
      pkg.version = '2.0.0'
      writeFileSync(join(d, 'package.json'), JSON.stringify(pkg, null, 2))
      writeFileSync(join(d, 'CITATION.cff'), 'title: t\nversion: 2.0.0\nlicense: x\n')
      writeFileSync(
        join(d, 'README.md'),
        readFileSync(join(d, 'README.md'), 'utf8').replaceAll('1.9.0', '2.0.0')
      )
      writeFileSync(join(d, 'CHANGELOG.md'), '# Changelog\n\n## 2.0.0\n\nReal notes.\n')
      return d
    },
    wantCode: 1,
    wantText: 'names a commit whose package.json says 1.9.0',
  },
  {
    name: 'a correct tree passes',
    dir: () => tree({}),
    wantCode: 0,
    wantText: 'version:check ok zeropoint-node@2.0.0',
  },
]

let failed = 0
for (const c of cases) {
  const dir = c.dir()
  try {
    const { code, out } = check(dir)
    const ok = code === c.wantCode && out.includes(c.wantText)
    if (!ok) {
      failed++
      console.error(`  ✗ ${c.name}`)
      console.error(`      want exit ${c.wantCode} containing ${JSON.stringify(c.wantText)}`)
      console.error(`      got  exit ${code}: ${out.trim().split('\n').join(' | ')}`)
    } else {
      console.log(`  ✓ ${c.name}`)
    }
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
}

if (failed > 0) {
  console.error(`version-seal self-test FAIL — ${failed}/${cases.length}`)
  process.exit(1)
}
console.log(`version-seal self-test ok — ${cases.length} cases, ${cases.length - 1} of them failures the gate must catch`)
