#!/usr/bin/env node
/**
 * Mint the animated vortex figure as a COMPUTED projection — not a drawing.
 *
 * Every coordinate, colour, edge and animation below is derived from the live
 * kernel (src/0) and the a432 hue map. Nothing is placed by eye. The figure is
 * then content-addressed with computeContentUuid folded over its own model, so
 * the receipt printed under it moves the instant any kernel fact it depends on
 * moves — and vortex:svg:check fails until the artifact is regenerated. That is
 * the whole claim: the figure is a proof-without-words of what is EXACT
 * (the throughVoid involution, the doubling closure, the gateway set), and it
 * cannot say anything the arithmetic does not. Tempo and hue are the only
 * chosen conventions, and they are labelled as such.
 *
 * Owns two artifacts, one receipt:
 *   - docs/public/vortex.svg           (served animated at /vortex.svg)
 *   - README.md VORTEX:BEGIN..END block (embeds the figure + prints the receipt)
 *
 * Regenerate: npm run vortex:svg · verify: npm run vortex:svg:check
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  VORTEX_ORBIT,
  VORTEX_AXIS,
  throughVoid,
  foldVortexReflection,
  vortexStrokeGateways,
  decodeVortexDashAngles,
} from '../src/0/index.ts'
import { hueForDigit } from '../src/0/3/6/9/1/2/4/8/7/5/1/a432.math.ts'
import { computeContentUuid } from '../src/integrity/content-uuid.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const svgPath = resolve(root, 'docs/public/vortex.svg')
const readmePath = resolve(root, 'README.md')
const BEGIN = '<!-- VORTEX:BEGIN — generated by scripts/vortex-svg.mjs; do not edit by hand -->'
const END = '<!-- VORTEX:END -->'

// ── Geometry (derived) ──────────────────────────────────────────────────────
// Digit d sits at angle -90° + 40°·(d mod 9): 9 at the top (12 o'clock), then
// 1..8 clockwise. Same layout as the static og:image — this is frame 0 of it.
const VIEW = 600
const C = VIEW / 2
const R = 210
const NODE_R = 34
const round = (n) => Number(n.toFixed(2))
const pos = (d) => {
  const a = ((-90 + 40 * (d % 9)) * Math.PI) / 180
  return { x: round(C + R * Math.cos(a)), y: round(C + R * Math.sin(a)) }
}

const DIGITS = [1, 2, 3, 4, 5, 6, 7, 8, 9]
const P = Object.fromEntries(DIGITS.map((d) => [d, pos(d)]))

// ── Kernel facts (derived) ──────────────────────────────────────────────────
const reflection = foldVortexReflection()
const stroke = vortexStrokeGateways()
const dash = decodeVortexDashAngles()

// Mirror pairs from the involution itself — deduped, fixed point excluded.
const mirrorPairs = reflection.pairs
  .filter((p) => !p.fixed && p.digit < p.mirror)
  .map((p) => [p.digit, p.mirror])
const fixedPoint = reflection.fixedPoints[0] // 5
// Gateways that land on the enneagram (the tour's 0 has no node).
const gateways = stroke.gateways.filter((d) => d >= 1 && d <= 9)

const nodes = DIGITS.map((d) => ({
  d,
  x: P[d].x,
  y: P[d].y,
  hue: hueForDigit(d),
  axis: VORTEX_AXIS.includes(d),
  gateway: gateways.includes(d),
}))

// ── Tempo (CONVENTION — labelled, not derived) ──────────────────────────────
// One hop per orbit node; the whole doubling cycle is orbit.length seconds.
// This is a chosen presentation rate, exactly like hue = 36d. Nothing about the
// arithmetic fixes it.
const CYCLE = VORTEX_ORBIT.length // seconds
const DUR = `${CYCLE}s`

// ── Content address: fold the receipt over the MODEL, not the SVG string ─────
// So the stamp attests to the geometry and the kernel facts, and is immune to
// cosmetic whitespace. Any drift in a coordinate, hue, edge, gateway or the
// closure moves it.
const model = {
  kind: 'vortex-figure',
  view: VIEW,
  nodes: nodes.map(({ d, x, y, hue, axis, gateway }) => ({ d, x, y, hue, axis, gateway })),
  orbitWalk: [...VORTEX_ORBIT],
  axis: [...VORTEX_AXIS],
  mirrorPairs,
  fixedPoint,
  gateways,
  weightedBearing: dash.weightedBearing,
  groupOrder: reflection.groupOrder,
  excess: reflection.excess,
  involution: reflection.involution,
  doublingCoversOrbit: reflection.doublingCoversOrbit,
  gapIsAxis: reflection.gapIsAxis,
  reflectionValid: reflection.valid,
  gatewaysSealed: stroke.computes,
}
const receipt = String(computeContentUuid(model))

// ── Render helpers ──────────────────────────────────────────────────────────
const nodeFill = (hue) => `hsl(${hue} 62% 52%)`
const polyPoints = (ds) => ds.map((d) => `${P[d].x},${P[d].y}`).join(' ')
const orbitPath =
  'M ' + VORTEX_ORBIT.map((d) => `${P[d].x} ${P[d].y}`).join(' L ') + ` L ${P[VORTEX_ORBIT[0]].x} ${P[VORTEX_ORBIT[0]].y} Z`

// A short pulse once per CYCLE, phase-offset per orbit node so the doubling
// walk lights each node in turn (1→2→4→8→7→5). begin is the node's index.
const pulse = (i) =>
  `<animate attributeName="r" begin="${i}s" dur="${DUR}" repeatCount="indefinite" ` +
  `keyTimes="0;0.04;0.09;1" values="${NODE_R};${NODE_R + 10};${NODE_R};${NODE_R}" calcMode="spline" ` +
  `keySplines="0.2 0 0.2 1;0.4 0 1 1;0 0 1 1"/>`

// The mirror flashes in the back half of the cycle: every pair chord fades in
// together, showing throughVoid mapping each digit to its complement at once.
const chordAnim =
  `<animate attributeName="stroke-opacity" dur="${DUR}" repeatCount="indefinite" ` +
  `keyTimes="0;0.5;0.6;0.9;1" values="0;0;0.85;0.85;0"/>`

const orbitNodeIndex = Object.fromEntries(VORTEX_ORBIT.map((d, i) => [d, i]))

const nodeSvg = nodes
  .map((n) => {
    const label =
      `<text x="${n.x}" y="${n.y + 1}" text-anchor="middle" dominant-baseline="central" ` +
      `class="digit">${n.d}</text>`
    const gatewayRing = n.gateway
      ? `<circle cx="${n.x}" cy="${n.y}" r="${NODE_R + 7}" class="gateway"/>`
      : ''
    const fixedRing =
      n.d === fixedPoint
        ? `<circle cx="${n.x}" cy="${n.y}" r="${NODE_R + 7}" class="fixed">` +
          `<animate attributeName="stroke-opacity" dur="${DUR}" repeatCount="indefinite" ` +
          `keyTimes="0;0.5;0.6;0.9;1" values="0.15;0.15;0.9;0.9;0.15"/></circle>`
        : ''
    const anim = n.d in orbitNodeIndex ? pulse(orbitNodeIndex[n.d]) : ''
    return (
      `${gatewayRing}${fixedRing}` +
      `<circle cx="${n.x}" cy="${n.y}" r="${NODE_R}" fill="${nodeFill(n.hue)}" class="node">${anim}</circle>` +
      label
    )
  })
  .join('\n    ')

const chordSvg = mirrorPairs
  .map(
    ([a, b]) =>
      `<line x1="${P[a].x}" y1="${P[a].y}" x2="${P[b].x}" y2="${P[b].y}" class="chord" stroke-opacity="0">${chordAnim}</line>`,
  )
  .join('\n    ')

const svg = `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/vortex-svg.mjs — do not edit by hand.
     Computed projection of src/0. Receipt ${receipt}. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${VIEW} ${VIEW}" role="img"
     aria-label="The vortex enneagram: the 3-6-9 gateway triangle, the 1-2-4-8-7-5 doubling loop, and the throughVoid mirror pairs. Computed projection of the ZeroPoint kernel.">
  <style>
    :root { --line: #3c3c43; --stamp: #8a8a94; }
    @media (prefers-color-scheme: dark) { :root { --line: #d0d0d8; --stamp: #7d7d8a; } }
    .guide  { fill: none; stroke: var(--line); stroke-opacity: 0.14; stroke-width: 1.5; }
    .hex    { fill: none; stroke: var(--line); stroke-opacity: 0.34; stroke-width: 2.5; stroke-linejoin: round; }
    .tri    { fill: none; stroke: var(--line); stroke-opacity: 0.62; stroke-width: 2.5; stroke-linejoin: round; }
    .chord  { stroke: var(--line); stroke-width: 2; stroke-dasharray: 5 6; }
    .node   { stroke: rgba(255,255,255,0.28); stroke-width: 1.5; }
    .gateway{ fill: none; stroke: var(--line); stroke-opacity: 0.5; stroke-width: 2; stroke-dasharray: 3 5; }
    .fixed  { fill: none; stroke: var(--line); stroke-width: 2.5; }
    .digit  { fill: #16161a; font: 700 30px ui-monospace, SFMono-Regular, Menlo, monospace; }
    .token  { fill: var(--line); }
    .stamp  { fill: var(--stamp); font: 400 12px ui-monospace, SFMono-Regular, Menlo, monospace; }
  </style>

  <circle class="guide" cx="${C}" cy="${C}" r="${R}"/>
  <polygon class="hex" points="${polyPoints(VORTEX_ORBIT)}"/>
  <polygon class="tri" points="${polyPoints(VORTEX_AXIS)}"/>

  <g class="chords">
    ${chordSvg}
  </g>

  <g class="nodes">
    ${nodeSvg}
  </g>

  <!-- Doubling walk: the token traverses 1→2→4→8→7→5→1, the orbit the kernel
       proves doubling closes on. Its path never touches the axis. -->
  <circle class="token" r="10">
    <animateMotion dur="${DUR}" repeatCount="indefinite" rotate="auto" path="${orbitPath}"/>
  </circle>

  <text class="stamp" x="${C}" y="${VIEW - 16}" text-anchor="middle">receipt ${receipt}</text>
</svg>
`

// ── README block ────────────────────────────────────────────────────────────
const readmeBlock = `${BEGIN}

<p align="center">
  <img src="docs/public/vortex.svg" width="420" alt="The vortex enneagram: the 3-6-9 gateway triangle, the 1-2-4-8-7-5 doubling loop, and the throughVoid mirror pairs — a computed projection of the kernel." />
</p>

The figure is **computed, not drawn** — every node, edge and colour is folded from \`src/0\` by \`scripts/vortex-svg.mjs\`, then content-addressed. It is a proof-without-words of what is *exact*: the doubling walk closes on the orbit \`{${VORTEX_ORBIT.join(', ')}}\` and never touches the axis \`{${VORTEX_AXIS.join(', ')}}\`; the dashed chords are \`throughVoid\` mapping each digit to its complement (\`${mirrorPairs.map(([a, b]) => `${a}↔${b}`).join(' · ')}\`, fixed only at **${fixedPoint}**); the dashed rings mark the gateways \`[${gateways.join(', ')}]\` where polarity reverses. The weighted bearing closes at **${dash.weightedBearing}**, and \`⟨D,M⟩\` has order **${reflection.groupOrder}** (excess **${reflection.excess}**). Tempo and \`hue = 36d\` are the only chosen conventions.

Its receipt is folded over that model, so a change to any of those facts moves the stamp and fails \`npm run vortex:svg:check\`. The figure cannot drift from the arithmetic without the build catching it.

Receipt: \`${receipt}\` · animated at [node.zeropoint.bg/vortex.svg](https://node.zeropoint.bg/vortex.svg)
${END}`

// ── Emit / check ────────────────────────────────────────────────────────────
const readme = readFileSync(readmePath, 'utf8')
const start = readme.indexOf(BEGIN)
const stop = readme.indexOf(END)
if (start === -1 || stop === -1) {
  console.error('README.md missing VORTEX markers — add the block placeholder first')
  process.exit(1)
}
const nextReadme = readme.slice(0, start) + readmeBlock + readme.slice(stop + END.length)

if (process.argv.includes('--check')) {
  let drift = false
  if (readFileSync(svgPath, 'utf8') !== svg) {
    console.error('docs/public/vortex.svg drift — run npm run vortex:svg')
    drift = true
  }
  if (readme !== nextReadme) {
    console.error('README.md vortex block drift — run npm run vortex:svg')
    drift = true
  }
  if (drift) process.exit(1)
  console.log('vortex:svg:check ok', receipt)
  process.exit(0)
}

writeFileSync(svgPath, svg)
writeFileSync(readmePath, nextReadme)
console.log('wrote docs/public/vortex.svg + README block', receipt)
